### ISSUE TITLE
Valgrantfile from cap02 dont work

### ISSUE THREAD

**Issue by danieagle** [PacktPublishing/Mastering-Ceph-Second-Edition#1]
Hi! 
valgrantfile from cap02 dont work and failed with message que osd file already exists.
I tried it com bento/ubuntu-16.04 and bento/ubuntu-20.04.

I used:
 linux host ubuntu 20.04
 virtual-box v6.1.10
 vagrant v2.2.6

Thanks in Advance,
Best wishes, Dani.

------------------------------------------------------------------------
A customization command failed:

["createhd", "--filename", "disk_osd-osd1", "--size", "10000"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["createhd", "--filename", "disk_osd-osd1", "--size", "10000"]

Stderr: 0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Failed to create medium
VBoxManage: error: Could not create the medium storage unit '/home/hds/soli/ceph-ansible/disk_osd-osd1.vdi'.
VBoxManage: error: VDI: cannot create image '/home/hds/soli/ceph-ansible/disk_osd-osd1.vdi' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage: error: Context: "RTEXITCODE handleCreateMedium(HandlerArg*)" at line 510 of file VBoxManageDisk.cpp
>

Please fix this customization and try again.

**Comment by fiskn** [comment]
As you mention it looks like the Vagrant command is failing due to the disk file already existing (VERR_ALREADY_EXISTS). Can you confirm if the disk file does exist in that path and remove it if it does?
